apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-starter.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "azure-starter.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "azure-starter.name" . }}
    spec:
      containers:
        - name: azure-starter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10